### ISSUE TITLE
If I want to use nginx forwarded to the other directory, how to configure?

### ISSUE THREAD

**Issue by gzlock** [knickers/mongo-express#1]
---------
dockr-compose.yml
https://github.com/gzlock/docker-web-server/blob/master/docker-compose.yml

-------
nginx config
https://github.com/gzlock/docker-web-server/blob/master/nginx_conf/default.conf

```
location /mongo-express{
    proxy_pass http://mongo_express:8081;
}
```

---------
And I change the Express-mongo project's config.default.js file,like this:

https://github.com/gzlock/docker-with-mongoexpress/blob/master/Dockerfile
```
ENV WEB_PATH="/mongo-express"
```

https://github.com/gzlock/docker-with-mongoexpress/blob/master/docker-entrypoint.sh
```
-e "s%(baseUrl:) '\/'%\1 '$WEB_PATH'%" \
```
But still failed，I don't know why,can you help me?
![-1](https://cloud.githubusercontent.com/assets/2311740/9976591/c1e3b9bc-5f1b-11e5-84ee-e768b176ed52.jpg)

**Comment by knickers** [comment]
Hi gzlock,

Did you close the issue because you figured it out?

**Comment by gzlock** [comment]
@knickers  yep,https://github.com/gzlock/docker-mongo-express/blob/master/docker-entrypoint.sh
modify the mongo-express's app.js the root path,ues:
``sed -i "s%'\/'%'$WEB_PATH'%" app.js``
