### ISSUE TITLE
Not being prompted to login even though `WEB_USER` and `WEB_PASSWORD` are specified.

### ISSUE THREAD

**Issue by rclayton-the-terrible** [knickers/mongo-express#2]
Maybe I'm doing something wrong here, but this is the command I'm executing:

```bash
docker run -d --restart=always --name mongo-express --link mongodb:mongo -e EDITOR_THEME="ambiance" -e WEB_USER="admin" -e WEB_PASS="password" -p 8081:8081 knickers/mongo-express
```

The website comes up perfectly, there's just no enforcement of the username and password.  Any ideas?

**Comment by knickers** [comment]
Looks like the mongo-express release I used didn't implement the web login feature. I'll update to a new version soon.

**Comment by knickers** [comment]
I've completed the updates, the web login credentials will now work. Take note of the new environment variable names though: ME_CONFIG_BASICAUTH_USERNAME and ME_CONFIG_BASICAUTH_PASSWORD.

**Comment by rclayton-the-terrible** [comment]
Thank you!
