### ISSUE TITLE
Can we merge?

### ISSUE THREAD

**Issue by wulfsolter** [knickers/mongo-express#4]
Holla,

I've recently taken over as maint for https://github.com/andzdroid/mongo-express as it was almost abandoned for a while. It would be pretty good to merge this functionality - it wasn't until someone lodged an issue with me that I even knew about your project!

**Comment by knickers** [comment]
Sure, I'd be OK merging. I don't really know how to go about it though :smirk:. Is there a standard way of doing that? Would we actually be merging or repos, or just working more closely together?

**Comment by wulfsolter** [comment]
Up to you :)

I've had a dig around, and I don't have admin privs to add you as a maintainer, but I'd really welcome a PR for the Dockerfile and merge in the updated documentation you've written! :)

https://help.github.com/articles/using-pull-requests/ has a whole lot of good info on PRs
