### ISSUE TITLE
issues on https://github.com/mongo-express/mongo-express-docker ?

### ISSUE THREAD

**Issue by tianon** [knickers/mongo-express#7]
Do you think it'd make sense to delete this repo so that https://github.com/mongo-express/mongo-express-docker changes from being a fork to being the "primary", and then re-fork here if necessary?

(Regardless, it'd probably be a good idea to turn on "issues" for the https://github.com/mongo-express/mongo-express-docker repo. :+1:)

**Comment by tianon** [comment]
Hmm, you could move this repo directly into the `mongo-express` organization and rebase the commits of the new repo on top or something, but since it was forked _from_ this one, it already has the commits, right?  It'd just be the PR and issue history that's here but isn't there, right?

**Comment by tianon** [comment]
I mean, move https://github.com/knickers/mongo-express into the https://github.com/mongo-express org (probably renaming it first so it doesn't conflict with the main mongo-express repo), then delete that other repo and let this one become the real source of truth.  You'd want to grab the commits from that other repo first, though.

**Comment by knickers** [comment]
Issues are turned on for https://github.com/mongo-express/mongo-express-docker, and I'm just going to delete this repo. The history is that expansive or important.
